version: 2.1

setup: << pipeline.parameters.run-setup >>

parameters:
  run-type:
    type: string
    default: "initial_run"
  run-setup:
    description: Whether it is a setup workflow or a continuation
    type: boolean
    default: true

orbs:
  continuation: circleci/continuation@0.2.0
  
jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - run:
          name: Generate Pipeline initial-config.yml file
          command: |
            chmod +x ./generate-config.sh |
            bash ./generate-config.sh "<< pipeline.parameters.run-type >>"
      - checkout
      - continuation/continue:
          parameters: '{}'
          configuration_path: .circleci/generated-config.yml
      
workflows:
  setup-workflow:
    when:
      and:
        - equal: [main, << pipeline.git.branch >>]
    jobs:
      - setup
