version: 2.1
setup: true

parameters:
  initial-workflow:
    type: boolean
    default: true
  new-pipileine-a:
    type: boolean
    default: false
  new-pipeline-b:
    type: boolean
    default: false
  new-pipeline-c:
    type: boolean
    default: false

orbs:
  continuation: circleci/continuation@0.2.0
  
jobs:
  setup:
    docker:
      - image: cimg/base:2022.09
    steps:
      - when:
          condition:
            equal: [ "true", pipeline.parameters.initial-workflow  >> ]
          steps:
            - checkout
            - continuation/continue:
                parameters: '{}'
                configuration_path: .circleci/initial-config.yml
      - when:
          condition:
            equal: [ "true", pipeline.parameters.new-pipileine-a  >> ]
          steps:
            - checkout
            - continuation/continue:
                parameters: '{}'
                configuration_path: .circleci/pipeline-a-config.yml
  setup-deploy-dev:
    executor: continuation/default
    steps:
      - checkout
      - continuation/continue:
          parameters: '{}'
          configuration_path: .circleci/dev-config.yml
      
workflows:
  setup-workflow:
    when:
      and:
        - equal: [main, << pipeline.git.branch >>]
    jobs:
      - setup
  setup-deploy-dev:
    when:
      and:
        - not:
            equal: [main, << pipeline.git.branch >>]
    jobs:
      - setup-deploy-dev
