version: 2.1

parameters:
  initial-workflow:
    type: boolean
    default: true
  new-pipileine-a:
    type: boolean
    default: false
  new-pipeline-b:
    type: boolean
    default: false

jobs:
  build:
    docker:
      - image: cimg/node:19.1.0
    steps:
      - checkout
      - run: node --version
  common-test:
    docker:
      - image: cimg/node:19.1.0
    steps:
      - checkout
      - run: node --version
  continue-with-new-api-a:
    docker:
      - image: cimg/node:19.1.0
    steps:
      - run:
          name: Call New Pipeline A
          command: |
            curl --request POST \
            --url https://circleci.com/api/v2/project/gh/jasurbek-khanjarov/cci-new-pipelines-api/pipeline \
            --header "Circle-Token: $CIRCLECI_TOKEN" \
            --header 'content-type: application/json' \
            --data '{"branch":"main", "parameters":{"new-pipileine-a": true, "run-setup": true}}'

  continue-with-new-api-b:
    docker:
      - image: cimg/node:19.1.0
    steps:
      - run: node --version
workflows:
  run-initial-workflow:
    when: << pipeline.parameters.initial-workflow >>
    jobs:
      - build
      - common-test
      - continue-with-new-api-a:
          requires:
            - common-test
      # - continue-with-new-api-b:
      #     requires:
      #       common-test
      
