version: 2.1

parameters:
  initial-workflow:
    type: boolean
    default: true
  new-pipileine-a:
    type: boolean
    default: false
  run-setup:
    description: Whether it is a setup workflow or a continuation
    type: boolean
    default: true

jobs:
  build-pipeline-a:
    docker:
      - image: cimg/node:19.1.0
    steps:
      - checkout
      - run: node --version
workflows:
  run-new-workflow-a:
    # when: << pipeline.parameters.new-pipileine-a >>
    jobs:
      - build
      
