version: 2.1

parameters:
  initial-workflow:
    type: boolean
    default: true
  new-pipileine-a:
    type: boolean
    default: false
  new-pipeline-b:
    type: boolean
    default: false

jobs:
  build-pipeline-a:
    docker:
      - image: cimg/node:19.1.0
    steps:
      - checkout
      - run: node --version
workflows:
  run-new-workflow-a:
    when: << pipeline.parameters.new-pipileine-a >>
    jobs:
      - build
      
