version: 2.1

parameters:
  initial-workflow:
    type: boolean
    default: true
  new-pipileine-a
    type: boolean
    default: false
  new-pipeline-b
    type: boolean
    default: false
  new-pipeline-c
    type: boolean
    default: false 

jobs:
  build:
    docker:
      - image: cimg/node:19.1.0
    steps:
      - checkout
      - run: node --version
      
workflows:

  run-initial-workflow:
    when: << pipeline.parameters.deploy-android >>
    jobs:
      - build
      
